version: 0.2

# env:
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#   parameter-store:
#     LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws s3 cp $ENV_PATH src
      - mv src/.env.production src/.env
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - |
        for container in nginx php-fpm
        do
          cp docker/${container}/Dockerfile ./
          docker build -t ${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG .
          docker tag ${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG
          rm -f ./Dockerfile
        done
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - |
        for container in nginx php-fpm
        do
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG
        done

# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   secondary-artifacts:
#     artifact1:
#       files:
#         - target/artifact-1.0.jar
#       discard-paths: yes
#     artifact2:
#       files:
#         - target/artifact-2.0.jar
#       discard-paths: yes
