version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws s3 cp $ENV_PATH src
      - mv src/.env.production src/.env
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - |
        for container in nginx php-fpm
        do
          cp docker/${container}/Dockerfile ./
          docker build -t ${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG .
          docker tag ${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG
          rm -f ./Dockerfile
        done
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - |
        for container in nginx php-fpm
        do
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_PREFIX}_${container}:$IMAGE_TAG
        done
