services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src/public:/var/www/html/public
      - ./docker/nginx/templates:/etc/nginx/templates
    environment:
      - FASTCGI_PASS=php-fpm:9000
    depends_on:
      - php-fpm
  php-fpm:
    build: 
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      - APP_ENV=local
    volumes:
      - ./src:/var/www/html
    ports:
      - 5173:5173
  mysql:
    image: mysql:9.1
    environment:
        MYSQL_DATABASE: todo
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  db: